name: aws_terraform

on:
  workflow_dispatch

jobs:
  aws-training-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: make init
        working-directory: aws_terraform

      - name: Run Python Script
        run: make workflow
        working-directory: aws_terraform

  build-docker-image:
    runs-on: ubuntu-latest
    needs:
      - aws-training-workflow
    steps:
      - name: Build Docker Image
        run: make build
